import { useState, useCallback, useRef } from "react";
import { Link } from "react-router-dom";

// ── Types ──

interface WizardConfig {
  projectId: string;
  region: string;
  saEmail: string;
  domain: string;
  senderEmail: string;
  dbPassword: string;
  cronSecret: string;
  firebaseApiKey: string;
  firebaseAuthDomain: string;
  firebaseProjectId: string;
  firebaseStorageBucket: string;
  firebaseMessagingSenderId: string;
  firebaseAppId: string;
  // internal confirmation flags
  _baaConfirmed: boolean;
  _apisConfirmed: boolean;
  _delegationConfirmed: boolean;
}

interface FieldError {
  field: string;
  message: string;
}

const TOTAL_STEPS = 9;

const REGIONS = [
  { value: "us-central1", label: "us-central1 (Iowa)" },
  { value: "us-east1", label: "us-east1 (South Carolina)" },
  { value: "us-east4", label: "us-east4 (Virginia)" },
  { value: "us-west1", label: "us-west1 (Oregon)" },
  { value: "us-west2", label: "us-west2 (Los Angeles)" },
];

const REQUIRED_APIS = [
  "sqladmin.googleapis.com",
  "run.googleapis.com",
  "cloudbuild.googleapis.com",
  "firebase.googleapis.com",
  "calendar-json.googleapis.com",
  "drive.googleapis.com",
  "gmail.googleapis.com",
  "docs.googleapis.com",
  "speech.googleapis.com",
  "aiplatform.googleapis.com",
  "cloudscheduler.googleapis.com",
  "secretmanager.googleapis.com",
  "artifactregistry.googleapis.com",
];

const DELEGATION_SCOPES = [
  "https://www.googleapis.com/auth/gmail.send",
  "https://www.googleapis.com/auth/calendar",
  "https://www.googleapis.com/auth/drive",
  "https://www.googleapis.com/auth/documents",
];

const STEP_NAMES = [
  "Welcome",
  "GCP Project",
  "Workspace BAA",
  "Enable APIs",
  "Service Account",
  "Domain Delegation",
  "Firebase Auth",
  "Domain + DNS",
  "Review + Deploy",
];

// ── Utilities ──

function generatePassword(length = 24): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
  const array = new Uint8Array(length);
  crypto.getRandomValues(array);
  return Array.from(array, (b) => chars[b % chars.length]).join("");
}

function generateDeployScript(config: WizardConfig): string {
  const p = config.projectId;
  const r = config.region;
  const sa = config.saEmail;
  const sender = config.senderEmail;
  const domain = config.domain;
  const dbPass = config.dbPassword;
  const cronSecret = config.cronSecret;

  return `#!/usr/bin/env bash
# ============================================================================
# Trellis EHR \u2014 Deployment Script
# Generated by the Trellis Setup Wizard
#
# This script deploys Trellis into your GCP project. Prerequisites:
#   - gcloud CLI installed and authenticated
#   - Docker installed and running
#   - sa-key.json in the current directory
#   - Trellis repository cloned (this should be run from the repo root)
#   - APIs enabled (done in wizard)
#   - Domain-wide delegation configured (done in wizard)
#
# Usage:
#   chmod +x deploy.sh
#   ./deploy.sh
# ============================================================================

set -euo pipefail

# \u2500\u2500 Configuration (from Setup Wizard) \u2500\u2500
PROJECT_ID="${p}"
REGION="${r}"
SA_EMAIL="${sa}"
SENDER_EMAIL="${sender}"
DOMAIN="${domain}"
DB_INSTANCE="trellis-db"
DB_NAME="trellis"
DB_USER="trellis"
DB_PASSWORD="${dbPass}"
CRON_SECRET="${cronSecret}"

# Firebase config (for frontend build)
FIREBASE_API_KEY="${config.firebaseApiKey}"
FIREBASE_AUTH_DOMAIN="${config.firebaseAuthDomain}"
FIREBASE_PROJECT_ID="${p}"
FIREBASE_STORAGE_BUCKET="${config.firebaseStorageBucket}"
FIREBASE_MESSAGING_SENDER_ID="${config.firebaseMessagingSenderId}"
FIREBASE_APP_ID="${config.firebaseAppId}"

# Derived
REGISTRY="\${REGION}-docker.pkg.dev/\${PROJECT_ID}/trellis"

# \u2500\u2500 Color output helpers \u2500\u2500
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

info()  { echo -e "\${BLUE}[INFO]\${NC}  $1"; }
ok()    { echo -e "\${GREEN}[OK]\${NC}    $1"; }
warn()  { echo -e "\${YELLOW}[WARN]\${NC}  $1"; }
error() { echo -e "\${RED}[ERROR]\${NC} $1"; exit 1; }

# \u2500\u2500 Preflight checks \u2500\u2500
info "Running preflight checks..."

command -v gcloud >/dev/null 2>&1 || error "gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install"
command -v docker >/dev/null 2>&1 || error "Docker not found. Install: https://docs.docker.com/get-docker/"
command -v psql >/dev/null 2>&1 || error "psql not found. Install PostgreSQL client tools."

if [ ! -f "sa-key.json" ]; then
    error "sa-key.json not found in current directory. Download it from GCP Console."
fi

if [ ! -f "backend/api/main.py" ]; then
    error "Run this script from the Trellis repository root directory."
fi

# Set the active project
gcloud config set project "\${PROJECT_ID}"
ok "GCP project set to \${PROJECT_ID}"

# ============================================================================
# 1. ARTIFACT REGISTRY
# ============================================================================
info "Setting up Artifact Registry..."

gcloud artifacts repositories describe trellis \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" >/dev/null 2>&1 || \\
gcloud artifacts repositories create trellis \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --repository-format=docker
ok "Artifact Registry repository ready"

# Configure Docker to authenticate with Artifact Registry
gcloud auth configure-docker "\${REGION}-docker.pkg.dev" --quiet
ok "Docker auth configured for Artifact Registry"

# ============================================================================
# 2. CLOUD SQL
# ============================================================================
info "Setting up Cloud SQL..."

# Check if instance already exists
if gcloud sql instances describe "\${DB_INSTANCE}" --project="\${PROJECT_ID}" >/dev/null 2>&1; then
    warn "Cloud SQL instance '\${DB_INSTANCE}' already exists. Skipping creation."
else
    info "Creating Cloud SQL instance (this takes 5-10 minutes)..."
    gcloud sql instances create "\${DB_INSTANCE}" \\
        --project="\${PROJECT_ID}" \\
        --database-version=POSTGRES_15 \\
        --tier=db-f1-micro \\
        --region="\${REGION}" \\
        --storage-type=SSD \\
        --storage-size=10GB \\
        --storage-auto-increase \\
        --backup \\
        --backup-start-time=04:00 \\
        --enable-point-in-time-recovery \\
        --maintenance-window-day=SUN \\
        --maintenance-window-hour=5 \\
        --availability-type=zonal \\
        --assign-ip

    ok "Cloud SQL instance created"
fi

# Get the connection name
DB_CONNECTION_NAME=\$(gcloud sql instances describe "\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" --format="value(connectionName)")
info "DB connection name: \${DB_CONNECTION_NAME}"

# Create database if not exists
if gcloud sql databases describe "\${DB_NAME}" --instance="\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" >/dev/null 2>&1; then
    warn "Database '\${DB_NAME}' already exists."
else
    gcloud sql databases create "\${DB_NAME}" --instance="\${DB_INSTANCE}" --project="\${PROJECT_ID}"
    ok "Database '\${DB_NAME}' created"
fi

# Set database user password
gcloud sql users set-password "\${DB_USER}" \\
    --instance="\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" \\
    --password="\${DB_PASSWORD}" 2>/dev/null || \\
gcloud sql users create "\${DB_USER}" \\
    --instance="\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" \\
    --password="\${DB_PASSWORD}"
ok "Database user configured"

# \u2500\u2500 Run migrations \u2500\u2500
info "Running database migrations..."

# Get public IP for migrations
DB_IP=\$(gcloud sql instances describe "\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" --format="value(ipAddresses[0].ipAddress)")

# Temporarily authorize current IP for migration
MY_IP=\$(curl -s https://api.ipify.org)
gcloud sql instances patch "\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" \\
    --authorized-networks="\${MY_IP}/32" \\
    --quiet

export PGPASSWORD="\${DB_PASSWORD}"
for migration in db/migrations/*.sql; do
    info "  Applying \$(basename \${migration})..."
    psql -h "\${DB_IP}" -U "\${DB_USER}" -d "\${DB_NAME}" -f "\${migration}" 2>&1 | \\
        grep -v "already exists" || true
done
unset PGPASSWORD
ok "All migrations applied"

# Remove temporary network authorization
gcloud sql instances patch "\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" \\
    --clear-authorized-networks \\
    --quiet
ok "Temporary network access removed"

# ============================================================================
# 3. SECRETS
# ============================================================================
info "Configuring secrets..."

# Store SA key as a secret
gcloud secrets create sa-key \\
    --project="\${PROJECT_ID}" \\
    --replication-policy=automatic 2>/dev/null || true
gcloud secrets versions add sa-key \\
    --project="\${PROJECT_ID}" \\
    --data-file=sa-key.json
ok "Service account key stored as secret"

# Grant SA access to the secret
gcloud secrets add-iam-policy-binding sa-key \\
    --project="\${PROJECT_ID}" \\
    --member="serviceAccount:\${SA_EMAIL}" \\
    --role="roles/secretmanager.secretAccessor"

# ============================================================================
# 4. BUILD AND DEPLOY CLOUD RUN SERVICES
# ============================================================================
info "Building and deploying services..."

# \u2500\u2500 API Service \u2500\u2500
info "Building API service..."
docker build -t "\${REGISTRY}/api:latest" \\
    -f backend/api/Dockerfile \\
    backend/
docker push "\${REGISTRY}/api:latest"
ok "API image pushed"

info "Deploying API service to Cloud Run..."
gcloud run deploy trellis-api \\
    --project="\${PROJECT_ID}" \\
    --region="\${REGION}" \\
    --image="\${REGISTRY}/api:latest" \\
    --platform=managed \\
    --allow-unauthenticated \\
    --port=8080 \\
    --memory=512Mi \\
    --cpu=1 \\
    --min-instances=0 \\
    --max-instances=10 \\
    --service-account="\${SA_EMAIL}" \\
    --set-secrets="/app/sa-key.json=sa-key:latest" \\
    --set-env-vars="\\
GCP_PROJECT_ID=\${PROJECT_ID},\\
GCP_REGION=\${REGION},\\
DB_CONNECTION_NAME=\${DB_CONNECTION_NAME},\\
DB_NAME=\${DB_NAME},\\
DB_USER=\${DB_USER},\\
DB_PASSWORD=\${DB_PASSWORD},\\
DATABASE_URL=postgresql://\${DB_USER}:\${DB_PASSWORD}@/\${DB_NAME}?host=/cloudsql/\${DB_CONNECTION_NAME},\\
SENDER_EMAIL=\${SENDER_EMAIL},\\
GOOGLE_APPLICATION_CREDENTIALS=/app/sa-key.json,\\
CRON_SECRET=\${CRON_SECRET},\\
ALLOWED_ORIGINS=https://\${DOMAIN}" \\
    --add-cloudsql-instances="\${DB_CONNECTION_NAME}"
ok "API service deployed"

API_URL=\$(gcloud run services describe trellis-api \\
    --project="\${PROJECT_ID}" --region="\${REGION}" \\
    --format="value(status.url)")
info "API URL: \${API_URL}"

# \u2500\u2500 Relay Service \u2500\u2500
info "Building relay service..."
docker build -t "\${REGISTRY}/relay:latest" \\
    -f backend/relay/Dockerfile \\
    backend/
docker push "\${REGISTRY}/relay:latest"
ok "Relay image pushed"

info "Deploying relay service to Cloud Run..."
gcloud run deploy trellis-relay \\
    --project="\${PROJECT_ID}" \\
    --region="\${REGION}" \\
    --image="\${REGISTRY}/relay:latest" \\
    --platform=managed \\
    --allow-unauthenticated \\
    --port=8080 \\
    --memory=512Mi \\
    --cpu=1 \\
    --min-instances=0 \\
    --max-instances=5 \\
    --timeout=3600 \\
    --service-account="\${SA_EMAIL}" \\
    --set-secrets="/app/sa-key.json=sa-key:latest" \\
    --set-env-vars="\\
GCP_PROJECT_ID=\${PROJECT_ID},\\
GCP_REGION=\${REGION},\\
DB_CONNECTION_NAME=\${DB_CONNECTION_NAME},\\
DB_NAME=\${DB_NAME},\\
DB_USER=\${DB_USER},\\
DB_PASSWORD=\${DB_PASSWORD},\\
DATABASE_URL=postgresql://\${DB_USER}:\${DB_PASSWORD}@/\${DB_NAME}?host=/cloudsql/\${DB_CONNECTION_NAME},\\
SENDER_EMAIL=\${SENDER_EMAIL},\\
GOOGLE_APPLICATION_CREDENTIALS=/app/sa-key.json,\\
API_BASE_URL=\${API_URL},\\
ALLOWED_ORIGINS=https://\${DOMAIN}" \\
    --add-cloudsql-instances="\${DB_CONNECTION_NAME}"
ok "Relay service deployed"

RELAY_URL=\$(gcloud run services describe trellis-relay \\
    --project="\${PROJECT_ID}" --region="\${REGION}" \\
    --format="value(status.url)")
info "Relay URL: \${RELAY_URL}"

# \u2500\u2500 Billing Service \u2500\u2500
info "Building billing service..."
docker build -t "\${REGISTRY}/billing:latest" \\
    -f backend/billing/Dockerfile \\
    backend/billing/
docker push "\${REGISTRY}/billing:latest"
ok "Billing image pushed"

info "Deploying billing service to Cloud Run..."
gcloud run deploy trellis-billing \\
    --project="\${PROJECT_ID}" \\
    --region="\${REGION}" \\
    --image="\${REGISTRY}/billing:latest" \\
    --platform=managed \\
    --allow-unauthenticated \\
    --port=8082 \\
    --memory=512Mi \\
    --cpu=1 \\
    --min-instances=0 \\
    --max-instances=5 \\
    --service-account="\${SA_EMAIL}" \\
    --set-secrets="/app/sa-key.json=sa-key:latest" \\
    --set-env-vars="\\
DATABASE_URL=postgresql://\${DB_USER}:\${DB_PASSWORD}@/\${DB_NAME}?host=/cloudsql/\${DB_CONNECTION_NAME},\\
ALLOWED_ORIGINS=https://\${DOMAIN},\\
CRON_SECRET=\${CRON_SECRET},\\
STEDI_API_KEY=CHANGE_ME,\\
STRIPE_SECRET_KEY=CHANGE_ME,\\
STRIPE_WEBHOOK_SECRET=CHANGE_ME,\\
TELNYX_API_KEY=CHANGE_ME,\\
TELNYX_FROM_NUMBER=CHANGE_ME,\\
PLATFORM_FEE_PERCENT=3.0,\\
GOOGLE_APPLICATION_CREDENTIALS=/app/sa-key.json" \\
    --add-cloudsql-instances="\${DB_CONNECTION_NAME}"
ok "Billing service deployed"

BILLING_URL=\$(gcloud run services describe trellis-billing \\
    --project="\${PROJECT_ID}" --region="\${REGION}" \\
    --format="value(status.url)")
info "Billing URL: \${BILLING_URL}"

warn "Update billing service env vars with real values:"
warn "  STEDI_API_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET,"
warn "  TELNYX_API_KEY, TELNYX_FROM_NUMBER, PLATFORM_FEE_PERCENT"

# \u2500\u2500 Frontend Service \u2500\u2500
info "Building frontend..."
docker build -t "\${REGISTRY}/frontend:latest" \\
    -f frontend/Dockerfile \\
    --build-arg VITE_FIREBASE_API_KEY="\${FIREBASE_API_KEY}" \\
    --build-arg VITE_FIREBASE_AUTH_DOMAIN="\${FIREBASE_AUTH_DOMAIN}" \\
    --build-arg VITE_FIREBASE_PROJECT_ID="\${FIREBASE_PROJECT_ID}" \\
    --build-arg VITE_FIREBASE_STORAGE_BUCKET="\${FIREBASE_STORAGE_BUCKET}" \\
    --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID="\${FIREBASE_MESSAGING_SENDER_ID}" \\
    --build-arg VITE_FIREBASE_APP_ID="\${FIREBASE_APP_ID}" \\
    --build-arg VITE_API_URL="\${API_URL}" \\
    --build-arg VITE_WS_URL="\${RELAY_URL}" \\
    frontend/
docker push "\${REGISTRY}/frontend:latest"
ok "Frontend image pushed"

info "Deploying frontend to Cloud Run..."
gcloud run deploy trellis-frontend \\
    --project="\${PROJECT_ID}" \\
    --region="\${REGION}" \\
    --image="\${REGISTRY}/frontend:latest" \\
    --platform=managed \\
    --allow-unauthenticated \\
    --port=8080 \\
    --memory=256Mi \\
    --cpu=1 \\
    --min-instances=0 \\
    --max-instances=5
ok "Frontend deployed"

FRONTEND_URL=\$(gcloud run services describe trellis-frontend \\
    --project="\${PROJECT_ID}" --region="\${REGION}" \\
    --format="value(status.url)")
info "Frontend URL: \${FRONTEND_URL}"

# ============================================================================
# 5. CLOUD SCHEDULER (cron jobs)
# ============================================================================
info "Setting up Cloud Scheduler cron jobs..."

# Process recordings \u2014 every 5 minutes
gcloud scheduler jobs create http trellis-process-recordings \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="*/5 * * * *" \\
    --uri="\${API_URL}/api/cron/process-recordings" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=300s \\
    --description="Process Meet recordings and generate transcripts" 2>/dev/null || \\
gcloud scheduler jobs update http trellis-process-recordings \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="*/5 * * * *" \\
    --uri="\${API_URL}/api/cron/process-recordings" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=300s
ok "process-recordings cron job configured"

# Send reminders \u2014 every hour
gcloud scheduler jobs create http trellis-send-reminders \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 * * * *" \\
    --uri="\${API_URL}/api/cron/send-reminders" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s \\
    --description="Send 24-hour appointment reminder emails" 2>/dev/null || \\
gcloud scheduler jobs update http trellis-send-reminders \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 * * * *" \\
    --uri="\${API_URL}/api/cron/send-reminders" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s
ok "send-reminders cron job configured"

# Check reconfirmations \u2014 every hour
gcloud scheduler jobs create http trellis-check-reconfirmations \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 * * * *" \\
    --uri="\${API_URL}/api/cron/check-reconfirmations" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s \\
    --description="Check for expired reconfirmation windows and release slots" 2>/dev/null || \\
gcloud scheduler jobs update http trellis-check-reconfirmations \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 * * * *" \\
    --uri="\${API_URL}/api/cron/check-reconfirmations" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s
ok "check-reconfirmations cron job configured"

# Check no-shows \u2014 every 15 minutes
gcloud scheduler jobs create http trellis-check-no-shows \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="*/15 * * * *" \\
    --uri="\${API_URL}/api/cron/check-no-shows" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s \\
    --description="Mark past-due appointments as no-show" 2>/dev/null || \\
gcloud scheduler jobs update http trellis-check-no-shows \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="*/15 * * * *" \\
    --uri="\${API_URL}/api/cron/check-no-shows" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s
ok "check-no-shows cron job configured"

# Check unsigned docs \u2014 daily at 6 AM
gcloud scheduler jobs create http trellis-check-unsigned-docs \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 6 * * *" \\
    --uri="\${API_URL}/api/cron/check-unsigned-docs" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s \\
    --description="Send reminders for unsigned consent documents" 2>/dev/null || \\
gcloud scheduler jobs update http trellis-check-unsigned-docs \\
    --project="\${PROJECT_ID}" \\
    --location="\${REGION}" \\
    --schedule="0 6 * * *" \\
    --uri="\${API_URL}/api/cron/check-unsigned-docs" \\
    --http-method=POST \\
    --headers="X-Cron-Secret=\${CRON_SECRET}" \\
    --attempt-deadline=120s
ok "check-unsigned-docs cron job configured"

# ============================================================================
# 6. CUSTOM DOMAIN MAPPING
# ============================================================================
info "Mapping custom domain..."
gcloud run domain-mappings create \\
    --project="\${PROJECT_ID}" \\
    --region="\${REGION}" \\
    --service=trellis-frontend \\
    --domain="\${DOMAIN}" 2>/dev/null || \\
    warn "Domain mapping may already exist or require verification."

# ============================================================================
# 7. SECURITY HARDENING
# ============================================================================
info "Applying security hardening..."

# Remove public IP access from Cloud SQL (Cloud Run uses Cloud SQL Connector)
gcloud sql instances patch "\${DB_INSTANCE}" \\
    --project="\${PROJECT_ID}" \\
    --clear-authorized-networks \\
    --quiet
ok "Cloud SQL public access locked down"

# ============================================================================
# 8. VERIFY DEPLOYMENT
# ============================================================================
info "Running health check..."
sleep 10  # Wait for services to stabilize

HEALTH_RESPONSE=\$(curl -s -X POST "\${API_URL}/api/health" || echo '{"status":"error"}')
echo ""
echo "\${HEALTH_RESPONSE}" | python3 -m json.tool 2>/dev/null || echo "\${HEALTH_RESPONSE}"
echo ""

# ============================================================================
# DEPLOYMENT COMPLETE
# ============================================================================
echo ""
echo -e "\${GREEN}============================================================\${NC}"
echo -e "\${GREEN}  Trellis deployment complete!\${NC}"
echo -e "\${GREEN}============================================================\${NC}"
echo ""
echo "  Services:"
echo "    Frontend:  \${FRONTEND_URL}"
echo "    API:       \${API_URL}"
echo "    Relay:     \${RELAY_URL}"
echo "    Billing:   \${BILLING_URL}"
echo ""
echo "  Custom domain: https://\${DOMAIN}"
echo ""
echo -e "  \${YELLOW}DNS Setup Required:\${NC}"
echo "    Add a CNAME record for '\${DOMAIN}' pointing to 'ghs.googlehosted.com'"
echo "    (This may take up to 24 hours to propagate)"
echo ""
echo "  Next steps:"
echo "    1. Add the DNS record above"
echo "    2. Add https://\${DOMAIN} to Firebase authorized domains"
echo "    3. Enable Meet auto-recording in Workspace Admin Console"
echo "    4. Visit https://\${DOMAIN} and sign in as the clinician"
echo "    5. Select 'Clinician' role and complete practice profile setup"
echo "    6. Share your Trellis URL with clients!"
echo ""
echo -e "  \${YELLOW}Important:\${NC}"
echo "    - Keep sa-key.json secure (do not commit to git)"
echo "    - Database password: stored in Cloud Run env vars"
echo "    - Cron secret: stored in Cloud Run env vars"
echo ""
`;
}

// ── Reusable sub-components ──

function CodeBlock({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [text]);

  return (
    <div className="relative bg-warm-800 text-warm-200 rounded-lg font-mono text-[0.8125rem] leading-relaxed overflow-x-auto my-3">
      <button
        onClick={handleCopy}
        className="absolute top-2 right-2 px-2 py-1 text-[0.7rem] bg-white/10 border border-white/20 text-warm-200 rounded hover:bg-white/20 hover:text-white transition-all"
      >
        {copied ? "Copied!" : "Copy"}
      </button>
      <pre className="p-4 pr-20 whitespace-pre-wrap break-all">{text}</pre>
    </div>
  );
}

function InfoBox({
  variant,
  title,
  children,
}: {
  variant: "info" | "warning" | "success";
  title: string;
  children: React.ReactNode;
}) {
  const styles = {
    info: "bg-blue-50 border-blue-200 text-blue-900",
    warning: "bg-amber-50 border-amber-200 text-amber-900",
    success: "bg-green-50 border-green-200 text-green-900",
  };

  return (
    <div className={`p-4 rounded-lg border text-sm leading-relaxed my-4 ${styles[variant]}`}>
      <strong className="block mb-1">{title}</strong>
      {children}
    </div>
  );
}

function FormField({
  label,
  helpText,
  error,
  children,
}: {
  label: string;
  helpText?: string;
  error?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mb-5">
      <label className="block text-sm font-medium text-warm-800 mb-1.5">
        {label}
      </label>
      {children}
      {helpText && !error && (
        <p className="text-xs text-warm-500 mt-1">{helpText}</p>
      )}
      {error && <p className="text-xs text-red-500 mt-1">{error}</p>}
    </div>
  );
}

function WizardInput({
  value,
  onChange,
  error,
  ...props
}: Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange"> & {
  value: string;
  onChange: (val: string) => void;
  error?: boolean;
}) {
  return (
    <input
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className={`w-full px-3.5 py-2.5 rounded-lg border text-sm text-warm-800 bg-white transition-all outline-none focus:ring-2 focus:ring-teal-500/20 ${
        error
          ? "border-red-400 focus:border-red-500"
          : "border-warm-200 focus:border-teal-500"
      }`}
      {...props}
    />
  );
}

function ConfirmCheckbox({
  checked,
  onChange,
  label,
  error,
}: {
  checked: boolean;
  onChange: (val: boolean) => void;
  label: string;
  error?: boolean;
}) {
  return (
    <label
      className={`flex items-start gap-3 p-4 bg-sage-50 border rounded-lg cursor-pointer my-4 transition-colors ${
        error ? "border-red-400" : "border-sage-200"
      }`}
    >
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="w-[18px] h-[18px] mt-0.5 accent-teal-600 cursor-pointer shrink-0"
      />
      <span className="text-sm leading-relaxed">{label}</span>
    </label>
  );
}

function ExternalLink({
  href,
  children,
}: {
  href: string;
  children: React.ReactNode;
}) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-teal-700 font-medium border-b border-dashed border-teal-300 hover:text-teal-900 hover:border-solid transition-colors"
    >
      {children}
    </a>
  );
}

function InstructionList({ children }: { children: React.ReactNode }) {
  return (
    <ol className="my-4 space-y-0 list-none counter-reset-step">
      {children}
    </ol>
  );
}

function InstructionItem({ children }: { children: React.ReactNode }) {
  return (
    <li className="relative pl-10 py-3 border-b border-warm-100 last:border-b-0 leading-relaxed text-sm instruction-item">
      {children}
    </li>
  );
}

// ── Step Components ──

function StepWelcome() {
  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Welcome to Trellis
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        This wizard will guide you through setting up Trellis in your own Google Cloud
        project and Google Workspace. It takes about 30 minutes.
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 my-6">
        {[
          {
            title: "Your Data, Your Control",
            desc: "Everything runs in your own GCP project. Patient data never leaves your infrastructure.",
          },
          {
            title: "HIPAA Compliant",
            desc: "Google Cloud BAA, encrypted at rest, audit logging, session timeouts, and more.",
          },
          {
            title: "AI-Powered Workflow",
            desc: "Voice intake, auto-transcription, AI note generation, and billing document creation.",
          },
          {
            title: "Google Workspace Integration",
            desc: "Calendar, Meet, Gmail, and Drive work together for a seamless experience.",
          },
        ].map((f) => (
          <div
            key={f.title}
            className="p-4 border border-warm-100 rounded-lg bg-warm-50"
          >
            <h4 className="text-sm font-semibold text-teal-700 mb-1">
              {f.title}
            </h4>
            <p className="text-xs text-warm-500 leading-snug">{f.desc}</p>
          </div>
        ))}
      </div>

      <InfoBox variant="info" title="What you will need:">
        <ul className="mt-2 ml-5 list-disc space-y-1">
          <li>A Google Workspace account (Business Standard or higher for Meet recording)</li>
          <li>A Google Cloud account with billing enabled</li>
          <li>A custom domain (for your practice's Trellis URL)</li>
          <li>About 30 minutes to complete the setup</li>
        </ul>
      </InfoBox>

      <InfoBox variant="warning" title="HIPAA Requirement">
        You must sign Google's Business Associate Agreement (BAA) as part of this setup.
        Google Workspace Business Standard or higher is required.
      </InfoBox>
    </>
  );
}

function StepGcpProject({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const fieldErr = (f: string) => errors.find((e) => e.field === f)?.message;

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Create a GCP Project
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Create a new Google Cloud project dedicated to your Trellis installation.
        This keeps your practice data isolated in its own project.
      </p>

      <InstructionList>
        <InstructionItem>
          Go to the{" "}
          <ExternalLink href="https://console.cloud.google.com/projectcreate">
            Google Cloud Console &rarr; Create Project
          </ExternalLink>
        </InstructionItem>
        <InstructionItem>
          Enter a project name (e.g., <strong>trellis-yourpractice</strong>). Note the{" "}
          <strong>Project ID</strong> shown below the name field.
        </InstructionItem>
        <InstructionItem>
          Select your organization (your Google Workspace domain) as the parent.
        </InstructionItem>
        <InstructionItem>
          Click <strong>Create</strong> and wait for the project to be ready.
        </InstructionItem>
        <InstructionItem>
          Ensure billing is enabled:{" "}
          <ExternalLink href="https://console.cloud.google.com/billing">
            Billing Console
          </ExternalLink>
          {" "}&mdash; link a billing account to your new project.
        </InstructionItem>
      </InstructionList>

      <FormField
        label="GCP Project ID"
        helpText="The Project ID (not name). Lowercase letters, numbers, and hyphens. 6-30 characters."
        error={fieldErr("projectId")}
      >
        <WizardInput
          value={config.projectId}
          onChange={(v) => setConfig((c) => ({ ...c, projectId: v.trim() }))}
          placeholder="e.g., trellis-yourpractice"
          error={!!fieldErr("projectId")}
        />
      </FormField>

      <FormField
        label="Preferred Region"
        helpText="Choose a region close to your practice for best performance."
      >
        <select
          value={config.region}
          onChange={(e) =>
            setConfig((c) => ({ ...c, region: e.target.value }))
          }
          className="w-full px-3.5 py-2.5 rounded-lg border border-warm-200 text-sm text-warm-800 bg-white transition-all outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20"
        >
          {REGIONS.map((r) => (
            <option key={r.value} value={r.value}>
              {r.label}
            </option>
          ))}
        </select>
      </FormField>
    </>
  );
}

function StepBaa({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const hasError = errors.some((e) => e.field === "_baaConfirmed");

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Sign Google Workspace BAA
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        HIPAA requires a Business Associate Agreement (BAA) with any vendor that handles
        Protected Health Information (PHI). Google provides this for Workspace and Cloud.
      </p>

      <InstructionList>
        <InstructionItem>
          Sign the <strong>Google Workspace BAA</strong>:{" "}
          <ExternalLink href="https://admin.google.com/ac/compliancecontrols">
            Admin Console &rarr; Account &rarr; Compliance
          </ExternalLink>
          <br />
          Look for "Google Workspace/Cloud Identity HIPAA BAA" and accept it.
        </InstructionItem>
        <InstructionItem>
          Sign the <strong>Google Cloud BAA</strong>: Go to your GCP project, then{" "}
          <ExternalLink href="https://console.cloud.google.com/iam-admin/settings">
            IAM & Admin &rarr; Settings
          </ExternalLink>
          {" "}and look for the "Google Cloud BAA" acceptance option. Alternatively, visit the{" "}
          <ExternalLink href="https://cloud.google.com/terms/baa">
            Cloud BAA page
          </ExternalLink>
          .
        </InstructionItem>
      </InstructionList>

      <InfoBox variant="warning" title="Important">
        Both BAAs must be signed before storing any patient data. Without the BAA,
        Google is not considered a HIPAA-covered business associate and your setup
        would not be compliant.
      </InfoBox>

      <ConfirmCheckbox
        checked={config._baaConfirmed}
        onChange={(v) => setConfig((c) => ({ ...c, _baaConfirmed: v }))}
        label="I have signed both the Google Workspace BAA and the Google Cloud BAA for my organization."
        error={hasError}
      />
    </>
  );
}

function StepApis({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const hasError = errors.some((e) => e.field === "_apisConfirmed");
  const gcloudCmd = `gcloud services enable \\\n  ${REQUIRED_APIS.join(" \\\n  ")} \\\n  --project=${config.projectId || "YOUR_PROJECT_ID"}`;

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Enable Required APIs
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Enable the Google Cloud APIs that Trellis needs. You can do this with a single
        gcloud command or through the Console.
      </p>

      <InfoBox variant="info" title="Quick method: Run this command">
        Open{" "}
        <ExternalLink href="https://console.cloud.google.com/cloudshell">
          Cloud Shell
        </ExternalLink>{" "}
        and paste the command below.
      </InfoBox>

      <CodeBlock text={gcloudCmd} />

      <p className="mt-4 mb-3 text-sm font-medium">APIs being enabled:</p>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-4">
        {REQUIRED_APIS.map((api) => (
          <div
            key={api}
            className="flex items-center gap-2 px-3 py-2 bg-warm-50 border border-warm-100 rounded-md text-[0.8125rem]"
          >
            <span className="text-green-500 font-bold">&#10003;</span>
            <span>{api.replace(".googleapis.com", "")}</span>
          </div>
        ))}
      </div>

      <ConfirmCheckbox
        checked={config._apisConfirmed}
        onChange={(v) => setConfig((c) => ({ ...c, _apisConfirmed: v }))}
        label="I have enabled all required APIs for my project."
        error={hasError}
      />
    </>
  );
}

function StepServiceAccount({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const fieldErr = (f: string) => errors.find((e) => e.field === f)?.message;
  const projectId = config.projectId || "YOUR_PROJECT_ID";
  const saName = "trellis-backend";
  const saEmail = `${saName}@${projectId}.iam.gserviceaccount.com`;

  const createCmd = `# Create the service account
gcloud iam service-accounts create ${saName} \\
  --display-name="Trellis Backend" \\
  --project=${projectId}

# Grant required roles
gcloud projects add-iam-policy-binding ${projectId} \\
  --member="serviceAccount:${saEmail}" \\
  --role="roles/cloudsql.client"

gcloud projects add-iam-policy-binding ${projectId} \\
  --member="serviceAccount:${saEmail}" \\
  --role="roles/aiplatform.user"

gcloud projects add-iam-policy-binding ${projectId} \\
  --member="serviceAccount:${saEmail}" \\
  --role="roles/run.admin"

gcloud projects add-iam-policy-binding ${projectId} \\
  --member="serviceAccount:${saEmail}" \\
  --role="roles/iam.serviceAccountTokenCreator"

gcloud projects add-iam-policy-binding ${projectId} \\
  --member="serviceAccount:${saEmail}" \\
  --role="roles/speech.client"

# Download the key file (keep this secure!)
gcloud iam service-accounts keys create sa-key.json \\
  --iam-account=${saEmail}`;

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Create Service Account
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Create a service account that Trellis uses to access Google APIs (Calendar, Gmail, Drive, etc.)
        and download its key file.
      </p>

      <InstructionList>
        <InstructionItem>
          Run the commands below in{" "}
          <ExternalLink href="https://console.cloud.google.com/cloudshell">
            Cloud Shell
          </ExternalLink>
          .
        </InstructionItem>
        <InstructionItem>
          The <code className="bg-warm-100 px-1.5 py-0.5 rounded text-[0.8125rem]">sa-key.json</code> file will be downloaded. Keep it secure &mdash; it grants access to your project's APIs.
        </InstructionItem>
        <InstructionItem>
          Enter the service account email below.
        </InstructionItem>
      </InstructionList>

      <CodeBlock text={createCmd} />

      <FormField
        label="Service Account Email"
        helpText="Format: name@project-id.iam.gserviceaccount.com"
        error={fieldErr("saEmail")}
      >
        <WizardInput
          value={config.saEmail}
          onChange={(v) => setConfig((c) => ({ ...c, saEmail: v.trim() }))}
          placeholder={saEmail}
          error={!!fieldErr("saEmail")}
        />
      </FormField>

      <InfoBox variant="warning" title="Security">
        The <code className="bg-amber-100 px-1 py-0.5 rounded text-[0.8125rem]">sa-key.json</code> file
        should never be committed to git or shared publicly. It will be uploaded as a Cloud Run secret
        during deployment.
      </InfoBox>
    </>
  );
}

function StepDelegation({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const fieldErr = (f: string) => errors.find((e) => e.field === f)?.message;
  const hasConfirmError = errors.some((e) => e.field === "_delegationConfirmed");
  const saEmail =
    config.saEmail || "trellis-backend@YOUR_PROJECT.iam.gserviceaccount.com";

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Enable Domain-Wide Delegation
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Domain-wide delegation allows the service account to send emails, manage calendar events,
        and access Drive on behalf of a Workspace user (e.g., your admin account).
      </p>

      <InstructionList>
        <InstructionItem>
          Go to{" "}
          <ExternalLink href="https://console.cloud.google.com/iam-admin/serviceaccounts">
            IAM &rarr; Service Accounts
          </ExternalLink>
          , click on the service account (
          <code className="bg-warm-100 px-1.5 py-0.5 rounded text-[0.8125rem]">
            {saEmail}
          </code>
          ).
        </InstructionItem>
        <InstructionItem>
          Under the <strong>Details</strong> tab, expand <strong>Advanced settings</strong>.
          Note the <strong>Client ID</strong> (a numeric string).
        </InstructionItem>
        <InstructionItem>
          Check <strong>"Enable Google Workspace Domain-wide Delegation"</strong> and save.
        </InstructionItem>
        <InstructionItem>
          Go to{" "}
          <ExternalLink href="https://admin.google.com/ac/owl/domainwidedelegation">
            Google Admin Console &rarr; Security &rarr; API controls &rarr; Domain-wide delegation
          </ExternalLink>
          .
        </InstructionItem>
        <InstructionItem>
          Click <strong>Add new</strong>. Enter the Client ID and add these OAuth scopes:
        </InstructionItem>
      </InstructionList>

      <div className="my-3">
        {DELEGATION_SCOPES.map((scope) => (
          <div
            key={scope}
            className="py-2 border-b border-warm-100 last:border-b-0 font-mono text-[0.8125rem] text-warm-600"
          >
            {scope}
          </div>
        ))}
      </div>

      <InfoBox variant="info" title="Copy all scopes at once:">
        <span className="text-xs">Paste the comma-separated string below into the Admin Console.</span>
      </InfoBox>
      <CodeBlock text={DELEGATION_SCOPES.join(",")} />

      <div className="mt-6">
        <FormField
          label="Workspace Sender Email"
          helpText="The Workspace user email that Trellis will send emails as and manage calendars for. Must be a user on your Workspace domain."
          error={fieldErr("senderEmail")}
        >
          <WizardInput
            value={config.senderEmail}
            onChange={(v) => setConfig((c) => ({ ...c, senderEmail: v.trim() }))}
            placeholder="e.g., admin@yourpractice.com"
            error={!!fieldErr("senderEmail")}
          />
        </FormField>
      </div>

      <ConfirmCheckbox
        checked={config._delegationConfirmed}
        onChange={(v) => setConfig((c) => ({ ...c, _delegationConfirmed: v }))}
        label="I have enabled domain-wide delegation and added all four OAuth scopes in the Admin Console."
        error={hasConfirmError}
      />
    </>
  );
}

function StepFirebase({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const fieldErr = (f: string) => errors.find((e) => e.field === f)?.message;
  const projectId = config.projectId || "YOUR_PROJECT_ID";

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Configure Firebase Auth
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Firebase handles user authentication (login/signup) for Trellis.
        You need to enable it and configure sign-in providers.
      </p>

      <InstructionList>
        <InstructionItem>
          Go to{" "}
          <ExternalLink
            href={`https://console.firebase.google.com/project/${projectId}/authentication/providers`}
          >
            Firebase Console &rarr; Authentication &rarr; Sign-in method
          </ExternalLink>
          . If Firebase is not yet added to this project, click "Add Firebase" first.
        </InstructionItem>
        <InstructionItem>
          Enable <strong>Google</strong> as a sign-in provider. Set the public-facing name
          to your practice name.
        </InstructionItem>
        <InstructionItem>
          Enable <strong>Email/Password</strong> as a sign-in provider.
        </InstructionItem>
        <InstructionItem>
          Go to{" "}
          <ExternalLink
            href={`https://console.firebase.google.com/project/${projectId}/settings/general`}
          >
            Project Settings &rarr; General
          </ExternalLink>
          . Scroll to "Your apps" &rarr; click the Web icon (
          <strong>&lt;/&gt;</strong>) to register a web app.
        </InstructionItem>
        <InstructionItem>
          Copy the Firebase config values from the code snippet shown.
        </InstructionItem>
      </InstructionList>

      <FormField label="API Key" error={fieldErr("firebaseApiKey")}>
        <WizardInput
          value={config.firebaseApiKey}
          onChange={(v) => setConfig((c) => ({ ...c, firebaseApiKey: v.trim() }))}
          placeholder="AIza..."
          error={!!fieldErr("firebaseApiKey")}
        />
      </FormField>

      <FormField label="Auth Domain" error={fieldErr("firebaseAuthDomain")}>
        <WizardInput
          value={config.firebaseAuthDomain}
          onChange={(v) => setConfig((c) => ({ ...c, firebaseAuthDomain: v.trim() }))}
          placeholder={`${projectId}.firebaseapp.com`}
          error={!!fieldErr("firebaseAuthDomain")}
        />
      </FormField>

      <FormField label="Storage Bucket" error={fieldErr("firebaseStorageBucket")}>
        <WizardInput
          value={config.firebaseStorageBucket}
          onChange={(v) =>
            setConfig((c) => ({ ...c, firebaseStorageBucket: v.trim() }))
          }
          placeholder={`${projectId}.firebasestorage.app`}
          error={!!fieldErr("firebaseStorageBucket")}
        />
      </FormField>

      <FormField
        label="Messaging Sender ID"
        error={fieldErr("firebaseMessagingSenderId")}
      >
        <WizardInput
          value={config.firebaseMessagingSenderId}
          onChange={(v) =>
            setConfig((c) => ({ ...c, firebaseMessagingSenderId: v.trim() }))
          }
          placeholder="123456789012"
          error={!!fieldErr("firebaseMessagingSenderId")}
        />
      </FormField>

      <FormField label="App ID" error={fieldErr("firebaseAppId")}>
        <WizardInput
          value={config.firebaseAppId}
          onChange={(v) => setConfig((c) => ({ ...c, firebaseAppId: v.trim() }))}
          placeholder="1:123456789012:web:abc123..."
          error={!!fieldErr("firebaseAppId")}
        />
      </FormField>
    </>
  );
}

function StepDomain({
  config,
  setConfig,
  errors,
}: {
  config: WizardConfig;
  setConfig: React.Dispatch<React.SetStateAction<WizardConfig>>;
  errors: FieldError[];
}) {
  const fieldErr = (f: string) => errors.find((e) => e.field === f)?.message;

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Custom Domain + DNS
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Set up your custom domain for the Trellis platform. Cloud Run will provide
        automatic HTTPS certificates.
      </p>

      <InstructionList>
        <InstructionItem>
          Decide on your domain. For example: <strong>app.yourpractice.com</strong>{" "}
          or <strong>ehr.yourpractice.com</strong>.
        </InstructionItem>
        <InstructionItem>
          After deployment, you will map this domain to your Cloud Run frontend service.
          The deployment script handles this automatically.
        </InstructionItem>
        <InstructionItem>
          You will need to add a DNS record (CNAME) pointing your subdomain to{" "}
          <code className="bg-warm-100 px-1.5 py-0.5 rounded text-[0.8125rem]">
            ghs.googlehosted.com
          </code>
          . Instructions will be in the deployment script output.
        </InstructionItem>
      </InstructionList>

      <FormField
        label="Practice Domain"
        helpText="The domain where Trellis will be accessible. Must be a domain you control."
        error={fieldErr("domain")}
      >
        <WizardInput
          value={config.domain}
          onChange={(v) => setConfig((c) => ({ ...c, domain: v.trim() }))}
          placeholder="e.g., app.yourpractice.com"
          error={!!fieldErr("domain")}
        />
      </FormField>

      <FormField
        label="Database Password"
        helpText="Password for the Cloud SQL database user. Leave empty to auto-generate a secure password."
        error={fieldErr("dbPassword")}
      >
        <WizardInput
          value={config.dbPassword}
          onChange={(v) => setConfig((c) => ({ ...c, dbPassword: v }))}
          placeholder="Auto-generated if left empty"
          error={!!fieldErr("dbPassword")}
        />
      </FormField>

      <FormField
        label="Cron Job Secret"
        helpText="Shared secret for authenticating Cloud Scheduler cron jobs. Leave empty to auto-generate."
        error={fieldErr("cronSecret")}
      >
        <WizardInput
          value={config.cronSecret}
          onChange={(v) => setConfig((c) => ({ ...c, cronSecret: v }))}
          placeholder="Auto-generated if left empty"
          error={!!fieldErr("cronSecret")}
        />
      </FormField>

      <InfoBox variant="info" title="Meet Recording Setup">
        After deployment, enable auto-recording in Google Workspace Admin Console:
        <br />
        Admin Console &rarr; Apps &rarr; Google Workspace &rarr; Google Meet &rarr;
        Recording settings &rarr; "Record all meetings automatically"
      </InfoBox>
    </>
  );
}

function StepDeploy({ config }: { config: WizardConfig }) {
  const [scriptCopied, setScriptCopied] = useState(false);
  const [scriptVisible, setScriptVisible] = useState(false);
  const script = generateDeployScript(config);

  function downloadScript() {
    const blob = new Blob([script], { type: "text/x-shellscript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "deploy.sh";
    a.click();
    URL.revokeObjectURL(url);
  }

  function copyScript() {
    navigator.clipboard.writeText(script).then(() => {
      setScriptCopied(true);
      setTimeout(() => setScriptCopied(false), 2000);
    });
  }

  return (
    <>
      <h2 className="font-display text-2xl font-bold text-warm-800 mb-2">
        Review & Deploy
      </h2>
      <p className="text-warm-500 text-[0.95rem] mb-6 leading-relaxed">
        Review your configuration and download the deployment script.
        The script will set up everything in your GCP project.
      </p>

      <h3 className="text-sm font-semibold mb-3">Configuration Summary</h3>
      <table className="w-full mb-6">
        <tbody>
          {[
            ["GCP Project", config.projectId],
            ["Region", config.region],
            ["Service Account", config.saEmail],
            ["Sender Email", config.senderEmail],
            ["Domain", config.domain],
            ["Firebase Project", config.firebaseProjectId],
          ].map(([label, val]) => (
            <tr key={label} className="border-b border-warm-100">
              <td className="py-2 text-sm font-medium text-warm-500 w-2/5">
                {label}
              </td>
              <td className="py-2 font-mono text-[0.8125rem] text-warm-800">
                {val}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <InfoBox variant="info" title="How to deploy">
        <ol className="mt-2 ml-5 list-decimal space-y-1">
          <li>Download the deployment script below.</li>
          <li>
            Place your{" "}
            <code className="bg-blue-100 px-1 py-0.5 rounded text-[0.8125rem]">
              sa-key.json
            </code>{" "}
            file in the same directory.
          </li>
          <li>
            Clone the Trellis repository:{" "}
            <code className="bg-blue-100 px-1 py-0.5 rounded text-[0.8125rem]">
              git clone https://github.com/your-org/trellis.git
            </code>
          </li>
          <li>
            Run the script from the repository root:{" "}
            <code className="bg-blue-100 px-1 py-0.5 rounded text-[0.8125rem]">
              chmod +x deploy.sh && ./deploy.sh
            </code>
          </li>
          <li>Follow the DNS instructions printed at the end.</li>
          <li>Visit your domain and log in as the first clinician!</li>
        </ol>
      </InfoBox>

      <div className="flex flex-wrap gap-3 my-6">
        <button
          onClick={downloadScript}
          className="inline-flex items-center gap-2 px-5 py-3 bg-teal-700 text-white rounded-lg font-semibold text-[0.9375rem] hover:bg-teal-800 transition-colors"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="currentColor"
          >
            <path d="M8 12l-4-4h2.5V2h3v6H12L8 12zM2 14h12v-1.5H2V14z" />
          </svg>
          Download deploy.sh
        </button>
        <button
          onClick={copyScript}
          className="inline-flex items-center gap-2 px-5 py-3 bg-white text-teal-700 border border-teal-300 rounded-lg font-semibold text-[0.9375rem] hover:bg-teal-50 transition-colors"
        >
          {scriptCopied ? "Copied!" : "Copy to Clipboard"}
        </button>
      </div>

      <div>
        <button
          onClick={() => setScriptVisible((v) => !v)}
          className="text-sm font-medium text-warm-600 hover:text-warm-800 cursor-pointer transition-colors mb-2"
        >
          {scriptVisible ? "Hide" : "Preview"} deployment script
        </button>
        {scriptVisible && (
          <pre className="bg-warm-800 text-warm-200 p-5 rounded-lg font-mono text-xs leading-relaxed max-h-96 overflow-auto whitespace-pre my-2">
            {script}
          </pre>
        )}
      </div>

      <InfoBox variant="success" title="After deployment">
        <ol className="mt-2 ml-5 list-decimal space-y-1">
          <li>
            Visit{" "}
            <code className="bg-green-100 px-1 py-0.5 rounded text-[0.8125rem]">
              https://{config.domain}
            </code>
          </li>
          <li>Click "Clinician Login" and sign in with your Google Workspace account.</li>
          <li>Select "Clinician" role when prompted.</li>
          <li>Complete the practice profile setup wizard.</li>
          <li>You are ready to accept clients!</li>
        </ol>
      </InfoBox>
    </>
  );
}

// ── Validation Functions ──

function validateStep(step: number, config: WizardConfig): FieldError[] {
  const errors: FieldError[] = [];

  switch (step) {
    case 0: // Welcome
      break;

    case 1: {
      // GCP Project
      const id = config.projectId;
      if (!id) {
        errors.push({ field: "projectId", message: "Project ID is required" });
      } else if (!/^[a-z][a-z0-9-]{4,28}[a-z0-9]$/.test(id)) {
        errors.push({
          field: "projectId",
          message:
            "Must be 6-30 characters: lowercase letters, numbers, hyphens. Must start with a letter.",
        });
      }
      break;
    }

    case 2: // BAA
      if (!config._baaConfirmed) {
        errors.push({
          field: "_baaConfirmed",
          message: "You must confirm BAA signing",
        });
      }
      break;

    case 3: // APIs
      if (!config._apisConfirmed) {
        errors.push({
          field: "_apisConfirmed",
          message: "You must confirm APIs are enabled",
        });
      }
      break;

    case 4: {
      // Service Account
      const email = config.saEmail;
      if (!email) {
        errors.push({
          field: "saEmail",
          message: "Service account email is required",
        });
      } else if (!email.endsWith(".iam.gserviceaccount.com")) {
        errors.push({
          field: "saEmail",
          message: "Must end with .iam.gserviceaccount.com",
        });
      } else if (!email.includes("@")) {
        errors.push({ field: "saEmail", message: "Invalid email format" });
      }
      break;
    }

    case 5: {
      // Delegation
      if (!config.senderEmail) {
        errors.push({
          field: "senderEmail",
          message: "Sender email is required",
        });
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.senderEmail)) {
        errors.push({
          field: "senderEmail",
          message: "Invalid email format",
        });
      }
      if (!config._delegationConfirmed) {
        errors.push({
          field: "_delegationConfirmed",
          message: "You must confirm delegation setup",
        });
      }
      break;
    }

    case 6: {
      // Firebase
      if (!config.firebaseApiKey) {
        errors.push({
          field: "firebaseApiKey",
          message: "API key is required",
        });
      } else if (!config.firebaseApiKey.startsWith("AIza")) {
        errors.push({
          field: "firebaseApiKey",
          message: 'Firebase API keys typically start with "AIza"',
        });
      }
      if (!config.firebaseAuthDomain) {
        errors.push({
          field: "firebaseAuthDomain",
          message: "Auth domain is required",
        });
      }
      if (!config.firebaseStorageBucket) {
        errors.push({
          field: "firebaseStorageBucket",
          message: "Storage bucket is required",
        });
      }
      if (!config.firebaseMessagingSenderId) {
        errors.push({
          field: "firebaseMessagingSenderId",
          message: "Messaging Sender ID is required",
        });
      } else if (!/^\d+$/.test(config.firebaseMessagingSenderId)) {
        errors.push({
          field: "firebaseMessagingSenderId",
          message: "Sender ID should be numeric",
        });
      }
      if (!config.firebaseAppId) {
        errors.push({ field: "firebaseAppId", message: "App ID is required" });
      }
      break;
    }

    case 7: {
      // Domain
      if (!config.domain) {
        errors.push({ field: "domain", message: "Domain is required" });
      } else if (
        !/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/.test(
          config.domain.toLowerCase()
        )
      ) {
        errors.push({
          field: "domain",
          message: "Enter a valid domain (e.g., app.yourpractice.com)",
        });
      }
      break;
    }

    case 8: // Deploy - no validation
      break;
  }

  return errors;
}

// ── Main Wizard Component ──

export default function SetupWizardPage() {
  const [currentStep, setCurrentStep] = useState(0);
  const [errors, setErrors] = useState<FieldError[]>([]);
  const contentRef = useRef<HTMLDivElement>(null);

  const [config, setConfig] = useState<WizardConfig>({
    projectId: "",
    region: "us-central1",
    saEmail: "",
    domain: "",
    senderEmail: "",
    dbPassword: "",
    cronSecret: "",
    firebaseApiKey: "",
    firebaseAuthDomain: "",
    firebaseProjectId: "",
    firebaseStorageBucket: "",
    firebaseMessagingSenderId: "",
    firebaseAppId: "",
    _baaConfirmed: false,
    _apisConfirmed: false,
    _delegationConfirmed: false,
  });

  const nextStep = useCallback(() => {
    const validationErrors = validateStep(currentStep, config);
    setErrors(validationErrors);
    if (validationErrors.length > 0) return;

    // Side effects on successful validation
    if (currentStep === 1) {
      // Auto-fill firebaseProjectId from projectId
      setConfig((c) => ({ ...c, firebaseProjectId: c.projectId }));
    }
    if (currentStep === 7) {
      // Auto-generate passwords if not provided
      setConfig((c) => ({
        ...c,
        dbPassword: c.dbPassword || generatePassword(24),
        cronSecret: c.cronSecret || generatePassword(32),
      }));
    }

    if (currentStep < TOTAL_STEPS - 1) {
      setCurrentStep((s) => s + 1);
      setErrors([]);
      window.scrollTo(0, 0);
    }
  }, [currentStep, config]);

  const prevStep = useCallback(() => {
    if (currentStep > 0) {
      setCurrentStep((s) => s - 1);
      setErrors([]);
      window.scrollTo(0, 0);
    }
  }, [currentStep]);

  const progressPct = (currentStep / (TOTAL_STEPS - 1)) * 100;

  return (
    <div className="min-h-screen bg-warm-50 flex items-start justify-center px-4 py-8">
      {/* Custom CSS for instruction list counters */}
      <style>{`
        .counter-reset-step { counter-reset: step; }
        .instruction-item { counter-increment: step; }
        .instruction-item::before {
          content: counter(step);
          position: absolute;
          left: 0;
          top: 0.75rem;
          width: 1.5rem;
          height: 1.5rem;
          background: #e8ece8;
          color: #3d5a4a;
          border-radius: 50%;
          font-size: 0.75rem;
          font-weight: 600;
          display: flex;
          align-items: center;
          justify-content: center;
        }
      `}</style>

      <div className="w-full max-w-[720px] bg-white rounded-2xl shadow-sm border border-warm-100 overflow-hidden">
        {/* Header */}
        <header className="flex items-center justify-between px-6 py-4 border-b border-warm-100">
          <Link to="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <svg viewBox="0 0 32 32" width="32" height="32" fill="none">
              <rect width="32" height="32" rx="8" fill="#4f6d5e" />
              <path
                d="M8 12h16M12 8v16M20 8v16"
                stroke="#fff"
                strokeWidth="2"
                strokeLinecap="round"
              />
            </svg>
            <span className="font-display text-xl font-bold text-warm-800">
              Trellis
            </span>
          </Link>
          <span className="text-sm text-warm-500 font-medium">
            Setup Wizard
          </span>
        </header>

        {/* Progress bar */}
        <div className="h-1 bg-warm-100">
          <div
            className="h-full bg-teal-700 transition-all duration-300 ease-out rounded-r-sm"
            style={{ width: `${progressPct}%` }}
          />
        </div>

        {/* Step dots */}
        <div className="flex justify-center gap-2 pt-4 px-6">
          {Array.from({ length: TOTAL_STEPS }).map((_, i) => (
            <div
              key={i}
              className={`w-2 h-2 rounded-full transition-all duration-300 ${
                i === currentStep
                  ? "bg-teal-700 scale-125"
                  : i < currentStep
                    ? "bg-teal-500"
                    : "bg-warm-200"
              }`}
              title={STEP_NAMES[i]}
            />
          ))}
        </div>

        {/* Step content */}
        <div ref={contentRef} className="px-6 py-8 min-h-[400px]">
          {currentStep === 0 && <StepWelcome />}
          {currentStep === 1 && (
            <StepGcpProject
              config={config}
              setConfig={setConfig}
              errors={errors}
            />
          )}
          {currentStep === 2 && (
            <StepBaa config={config} setConfig={setConfig} errors={errors} />
          )}
          {currentStep === 3 && (
            <StepApis config={config} setConfig={setConfig} errors={errors} />
          )}
          {currentStep === 4 && (
            <StepServiceAccount
              config={config}
              setConfig={setConfig}
              errors={errors}
            />
          )}
          {currentStep === 5 && (
            <StepDelegation
              config={config}
              setConfig={setConfig}
              errors={errors}
            />
          )}
          {currentStep === 6 && (
            <StepFirebase
              config={config}
              setConfig={setConfig}
              errors={errors}
            />
          )}
          {currentStep === 7 && (
            <StepDomain
              config={config}
              setConfig={setConfig}
              errors={errors}
            />
          )}
          {currentStep === 8 && <StepDeploy config={config} />}
        </div>

        {/* Footer navigation */}
        <footer className="flex items-center justify-between px-6 py-4 border-t border-warm-100 bg-warm-50">
          {currentStep > 0 ? (
            <button
              onClick={prevStep}
              className="px-5 py-2.5 text-sm font-medium text-warm-600 bg-white border border-warm-200 rounded-lg hover:bg-warm-50 hover:border-warm-300 transition-all"
            >
              Back
            </button>
          ) : (
            <div />
          )}

          <span className="text-[0.8125rem] text-warm-500">
            Step {currentStep + 1} of {TOTAL_STEPS}
          </span>

          {currentStep < TOTAL_STEPS - 1 ? (
            <button
              onClick={nextStep}
              className="px-5 py-2.5 text-sm font-medium text-white bg-teal-700 rounded-lg hover:bg-teal-800 transition-all"
            >
              Continue
            </button>
          ) : (
            <div />
          )}
        </footer>
      </div>
    </div>
  );
}
